apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "CRA"
  description: "Test Desc"
  annotations:
    github.com/project-slug: Rinat/test-2
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/guests"
